import { Country } from "../entities/country.entity";

export const countries: Country[] = [
  {
    currency: "AFN",
    phoneCode: "+93",
    name: "Afghanistan",
    isoCode: "AF",
  },
  {
    currency: "EUR",
    phoneCode: "+358-18",
    name: "Aland Islands",
    isoCode: "AX",
  },
  {
    currency: "ALL",
    phoneCode: "+355",
    name: "Albania",
    isoCode: "AL",
  },
  {
    currency: "DZD",
    phoneCode: "+213",
    name: "Algeria",
    isoCode: "DZ",
  },
  {
    currency: "USD",
    phoneCode: "+1-684",
    name: "American Samoa",
    isoCode: "AS",
  },
  {
    currency: "EUR",
    phoneCode: "+376",
    name: "Andorra",
    isoCode: "AD",
  },
  {
    currency: "AOA",
    phoneCode: "+244",
    name: "Angola",
    isoCode: "AO",
  },
  {
    currency: "XCD",
    phoneCode: "+1-264",
    name: "Anguilla",
    isoCode: "AI",
  },
  {
    currency: "AAD",
    phoneCode: "+672",
    name: "Antarctica",
    isoCode: "AQ",
  },
  {
    currency: "XCD",
    phoneCode: "+1-268",
    name: "Antigua And Barbuda",
    isoCode: "AG",
  },
  {
    currency: "ARS",
    phoneCode: "+54",
    name: "Argentina",
    isoCode: "AR",
  },
  {
    currency: "AMD",
    phoneCode: "+374",
    name: "Armenia",
    isoCode: "AM",
  },
  {
    currency: "AWG",
    phoneCode: "+297",
    name: "Aruba",
    isoCode: "AW",
  },
  {
    currency: "AUD",
    phoneCode: "+61",
    name: "Australia",
    isoCode: "AU",
  },
  {
    currency: "EUR",
    phoneCode: "+43",
    name: "Austria",
    isoCode: "AT",
  },
  {
    currency: "AZN",
    phoneCode: "+994",
    name: "Azerbaijan",
    isoCode: "AZ",
  },
  {
    currency: "BSD",
    phoneCode: "+1-242",
    name: "The Bahamas",
    isoCode: "BS",
  },
  {
    currency: "BHD",
    phoneCode: "+973",
    name: "Bahrain",
    isoCode: "BH",
  },
  {
    currency: "BDT",
    phoneCode: "+880",
    name: "Bangladesh",
    isoCode: "BD",
  },
  {
    currency: "BBD",
    phoneCode: "+1-246",
    name: "Barbados",
    isoCode: "BB",
  },
  {
    currency: "BYN",
    phoneCode: "+375",
    name: "Belarus",
    isoCode: "BY",
  },
  {
    currency: "EUR",
    phoneCode: "+32",
    name: "Belgium",
    isoCode: "BE",
  },
  {
    currency: "BZD",
    phoneCode: "+501",
    name: "Belize",
    isoCode: "BZ",
  },
  {
    currency: "XOF",
    phoneCode: "+229",
    name: "Benin",
    isoCode: "BJ",
  },
  {
    currency: "BMD",
    phoneCode: "+1-441",
    name: "Bermuda",
    isoCode: "BM",
  },
  {
    currency: "BTN",
    phoneCode: "+975",
    name: "Bhutan",
    isoCode: "BT",
  },
  {
    currency: "BOB",
    phoneCode: "+591",
    name: "Bolivia",
    isoCode: "BO",
  },
  {
    currency: "BAM",
    phoneCode: "+387",
    name: "Bosnia and Herzegovina",
    isoCode: "BA",
  },
  {
    currency: "BWP",
    phoneCode: "+267",
    name: "Botswana",
    isoCode: "BW",
  },
  {
    currency: "NOK",
    phoneCode: "+0055",
    name: "Bouvet Island",
    isoCode: "BV",
  },
  {
    currency: "BRL",
    phoneCode: "+55",
    name: "Brazil",
    isoCode: "BR",
  },
  {
    currency: "USD",
    phoneCode: "+246",
    name: "British Indian Ocean Territory",
    isoCode: "IO",
  },
  {
    currency: "BND",
    phoneCode: "+673",
    name: "Brunei",
    isoCode: "BN",
  },
  {
    currency: "BGN",
    phoneCode: "+359",
    name: "Bulgaria",
    isoCode: "BG",
  },
  {
    currency: "XOF",
    phoneCode: "+226",
    name: "Burkina Faso",
    isoCode: "BF",
  },
  {
    currency: "BIF",
    phoneCode: "+257",
    name: "Burundi",
    isoCode: "BI",
  },
  {
    currency: "KHR",
    phoneCode: "+855",
    name: "Cambodia",
    isoCode: "KH",
  },
  {
    currency: "XAF",
    phoneCode: "+237",
    name: "Cameroon",
    isoCode: "CM",
  },
  {
    currency: "CAD",
    phoneCode: "+1",
    name: "Canada",
    isoCode: "CA",
  },
  {
    currency: "CVE",
    phoneCode: "+238",
    name: "Cape Verde",
    isoCode: "CV",
  },
  {
    currency: "KYD",
    phoneCode: "+1-345",
    name: "Cayman Islands",
    isoCode: "KY",
  },
  {
    currency: "XAF",
    phoneCode: "+236",
    name: "Central African Republic",
    isoCode: "CF",
  },
  {
    currency: "XAF",
    phoneCode: "+235",
    name: "Chad",
    isoCode: "TD",
  },
  {
    currency: "CLP",
    phoneCode: "+56",
    name: "Chile",
    isoCode: "CL",
  },
  {
    currency: "CNY",
    phoneCode: "+86",
    name: "China",
    isoCode: "CN",
  },
  {
    currency: "AUD",
    phoneCode: "+61",
    name: "Christmas Island",
    isoCode: "CX",
  },
  {
    currency: "AUD",
    phoneCode: "+61",
    name: "Cocos (Keeling) Islands",
    isoCode: "CC",
  },
  {
    currency: "COP",
    phoneCode: "+57",
    name: "Colombia",
    isoCode: "CO",
  },
  {
    currency: "KMF",
    phoneCode: "+269",
    name: "Comoros",
    isoCode: "KM",
  },
  {
    currency: "XAF",
    phoneCode: "+242",
    name: "Congo",
    isoCode: "CG",
  },
  {
    currency: "CDF",
    phoneCode: "+243",
    name: "Democratic Republic of the Congo",
    isoCode: "CD",
  },
  {
    currency: "NZD",
    phoneCode: "+682",
    name: "Cook Islands",
    isoCode: "CK",
  },
  {
    currency: "CRC",
    phoneCode: "+506",
    name: "Costa Rica",
    isoCode: "CR",
  },
  {
    currency: "XOF",
    phoneCode: "+225",
    name: "Cote D'Ivoire (Ivory Coast)",
    isoCode: "CI",
  },
  {
    currency: "HRK",
    phoneCode: "+385",
    name: "Croatia",
    isoCode: "HR",
  },
  {
    currency: "CUP",
    phoneCode: "+53",
    name: "Cuba",
    isoCode: "CU",
  },
  {
    currency: "EUR",
    phoneCode: "+357",
    name: "Cyprus",
    isoCode: "CY",
  },
  {
    currency: "CZK",
    phoneCode: "+420",
    name: "Czech Republic",
    isoCode: "CZ",
  },
  {
    currency: "DKK",
    phoneCode: "+45",
    name: "Denmark",
    isoCode: "DK",
  },
  {
    currency: "DJF",
    phoneCode: "+253",
    name: "Djibouti",
    isoCode: "DJ",
  },
  {
    currency: "XCD",
    phoneCode: "+1-767",
    name: "Dominica",
    isoCode: "DM",
  },
  {
    currency: "DOP",
    phoneCode: "+1-809 and 1-829",
    name: "Dominican Republic",
    isoCode: "DO",
  },
  {
    currency: "USD",
    phoneCode: "+670",
    name: "East Timor",
    isoCode: "TL",
  },
  {
    currency: "USD",
    phoneCode: "+593",
    name: "Ecuador",
    isoCode: "EC",
  },
  {
    currency: "EGP",
    phoneCode: "+20",
    name: "Egypt",
    isoCode: "EG",
  },
  {
    currency: "USD",
    phoneCode: "+503",
    name: "El Salvador",
    isoCode: "SV",
  },
  {
    currency: "XAF",
    phoneCode: "+240",
    name: "Equatorial Guinea",
    isoCode: "GQ",
  },
  {
    currency: "ERN",
    phoneCode: "+291",
    name: "Eritrea",
    isoCode: "ER",
  },
  {
    currency: "EUR",
    phoneCode: "+372",
    name: "Estonia",
    isoCode: "EE",
  },
  {
    currency: "ETB",
    phoneCode: "+251",
    name: "Ethiopia",
    isoCode: "ET",
  },
  {
    currency: "FKP",
    phoneCode: "+500",
    name: "Falkland Islands",
    isoCode: "FK",
  },
  {
    currency: "DKK",
    phoneCode: "+298",
    name: "Faroe Islands",
    isoCode: "FO",
  },
  {
    currency: "FJD",
    phoneCode: "+679",
    name: "Fiji Islands",
    isoCode: "FJ",
  },
  {
    currency: "EUR",
    phoneCode: "+358",
    name: "Finland",
    isoCode: "FI",
  },
  {
    currency: "EUR",
    phoneCode: "+33",
    name: "France",
    isoCode: "FR",
  },
  {
    currency: "EUR",
    phoneCode: "+594",
    name: "French Guiana",
    isoCode: "GF",
  },
  {
    currency: "XPF",
    phoneCode: "+689",
    name: "French Polynesia",
    isoCode: "PF",
  },
  {
    currency: "EUR",
    phoneCode: "+262",
    name: "French Southern Territories",
    isoCode: "TF",
  },
  {
    currency: "XAF",
    phoneCode: "+241",
    name: "Gabon",
    isoCode: "GA",
  },
  {
    currency: "GMD",
    phoneCode: "+220",
    name: "The Gambia",
    isoCode: "GM",
  },
  {
    currency: "GEL",
    phoneCode: "+995",
    name: "Georgia",
    isoCode: "GE",
  },
  {
    currency: "EUR",
    phoneCode: "+49",
    name: "Germany",
    isoCode: "DE",
  },
  {
    currency: "GHS",
    phoneCode: "+233",
    name: "Ghana",
    isoCode: "GH",
  },
  {
    currency: "GIP",
    phoneCode: "+350",
    name: "Gibraltar",
    isoCode: "GI",
  },
  {
    currency: "EUR",
    phoneCode: "+30",
    name: "Greece",
    isoCode: "GR",
  },
  {
    currency: "DKK",
    phoneCode: "+299",
    name: "Greenland",
    isoCode: "GL",
  },
  {
    currency: "XCD",
    phoneCode: "+1-473",
    name: "Grenada",
    isoCode: "GD",
  },
  {
    currency: "EUR",
    phoneCode: "+590",
    name: "Guadeloupe",
    isoCode: "GP",
  },
  {
    currency: "USD",
    phoneCode: "+1-671",
    name: "Guam",
    isoCode: "GU",
  },
  {
    currency: "GTQ",
    phoneCode: "+502",
    name: "Guatemala",
    isoCode: "GT",
  },
  {
    currency: "GBP",
    phoneCode: "+44-1481",
    name: "Guernsey and Alderney",
    isoCode: "GG",
  },
  {
    currency: "GNF",
    phoneCode: "+224",
    name: "Guinea",
    isoCode: "GN",
  },
  {
    currency: "XOF",
    phoneCode: "+245",
    name: "Guinea-Bissau",
    isoCode: "GW",
  },
  {
    currency: "GYD",
    phoneCode: "+592",
    name: "Guyana",
    isoCode: "GY",
  },
  {
    currency: "HTG",
    phoneCode: "+509",
    name: "Haiti",
    isoCode: "HT",
  },
  {
    currency: "AUD",
    phoneCode: "+672",
    name: "Heard Island and McDonald Islands",
    isoCode: "HM",
  },
  {
    currency: "HNL",
    phoneCode: "+504",
    name: "Honduras",
    isoCode: "HN",
  },
  {
    currency: "HKD",
    phoneCode: "+852",
    name: "Hong Kong S.A.R.",
    isoCode: "HK",
  },
  {
    currency: "HUF",
    phoneCode: "+36",
    name: "Hungary",
    isoCode: "HU",
  },
  {
    currency: "ISK",
    phoneCode: "+354",
    name: "Iceland",
    isoCode: "IS",
  },
  {
    currency: "INR",
    phoneCode: "+91",
    name: "India",
    isoCode: "IN",
  },
  {
    currency: "IDR",
    phoneCode: "+62",
    name: "Indonesia",
    isoCode: "ID",
  },
  {
    currency: "IRR",
    phoneCode: "+98",
    name: "Iran",
    isoCode: "IR",
  },
  {
    currency: "IQD",
    phoneCode: "+964",
    name: "Iraq",
    isoCode: "IQ",
  },
  {
    currency: "EUR",
    phoneCode: "+353",
    name: "Ireland",
    isoCode: "IE",
  },
  {
    currency: "ILS",
    phoneCode: "+972",
    name: "Israel",
    isoCode: "IL",
  },
  {
    currency: "EUR",
    phoneCode: "+39",
    name: "Italy",
    isoCode: "IT",
  },
  {
    currency: "JMD",
    phoneCode: "+1-876",
    name: "Jamaica",
    isoCode: "JM",
  },
  {
    currency: "JPY",
    phoneCode: "+81",
    name: "Japan",
    isoCode: "JP",
  },
  {
    currency: "GBP",
    phoneCode: "+44-1534",
    name: "Jersey",
    isoCode: "JE",
  },
  {
    currency: "JOD",
    phoneCode: "+962",
    name: "Jordan",
    isoCode: "JO",
  },
  {
    currency: "KZT",
    phoneCode: "+7",
    name: "Kazakhstan",
    isoCode: "KZ",
  },
  {
    currency: "KES",
    phoneCode: "+254",
    name: "Kenya",
    isoCode: "KE",
  },
  {
    currency: "AUD",
    phoneCode: "+686",
    name: "Kiribati",
    isoCode: "KI",
  },
  {
    currency: "KPW",
    phoneCode: "+850",
    name: "North Korea",
    isoCode: "KP",
  },
  {
    currency: "KRW",
    phoneCode: "+82",
    name: "South Korea",
    isoCode: "KR",
  },
  {
    currency: "KWD",
    phoneCode: "+965",
    name: "Kuwait",
    isoCode: "KW",
  },
  {
    currency: "KGS",
    phoneCode: "+996",
    name: "Kyrgyzstan",
    isoCode: "KG",
  },
  {
    currency: "LAK",
    phoneCode: "+856",
    name: "Laos",
    isoCode: "LA",
  },
  {
    currency: "EUR",
    phoneCode: "+371",
    name: "Latvia",
    isoCode: "LV",
  },
  {
    currency: "LBP",
    phoneCode: "+961",
    name: "Lebanon",
    isoCode: "LB",
  },
  {
    currency: "LSL",
    phoneCode: "+266",
    name: "Lesotho",
    isoCode: "LS",
  },
  {
    currency: "LRD",
    phoneCode: "+231",
    name: "Liberia",
    isoCode: "LR",
  },
  {
    currency: "LYD",
    phoneCode: "+218",
    name: "Libya",
    isoCode: "LY",
  },
  {
    currency: "CHF",
    phoneCode: "+423",
    name: "Liechtenstein",
    isoCode: "LI",
  },
  {
    currency: "EUR",
    phoneCode: "+370",
    name: "Lithuania",
    isoCode: "LT",
  },
  {
    currency: "EUR",
    phoneCode: "+352",
    name: "Luxembourg",
    isoCode: "LU",
  },
  {
    currency: "MOP",
    phoneCode: "+853",
    name: "Macau S.A.R.",
    isoCode: "MO",
  },
  {
    currency: "MKD",
    phoneCode: "+389",
    name: "Macedonia",
    isoCode: "MK",
  },
  {
    currency: "MGA",
    phoneCode: "+261",
    name: "Madagascar",
    isoCode: "MG",
  },
  {
    currency: "MWK",
    phoneCode: "+265",
    name: "Malawi",
    isoCode: "MW",
  },
  {
    currency: "MYR",
    phoneCode: "+60",
    name: "Malaysia",
    isoCode: "MY",
  },
  {
    currency: "MVR",
    phoneCode: "+960",
    name: "Maldives",
    isoCode: "MV",
  },
  {
    currency: "XOF",
    phoneCode: "+223",
    name: "Mali",
    isoCode: "ML",
  },
  {
    currency: "EUR",
    phoneCode: "+356",
    name: "Malta",
    isoCode: "MT",
  },
  {
    currency: "GBP",
    phoneCode: "+44-1624",
    name: "Man (Isle of)",
    isoCode: "IM",
  },
  {
    currency: "USD",
    phoneCode: "+692",
    name: "Marshall Islands",
    isoCode: "MH",
  },
  {
    currency: "EUR",
    phoneCode: "+596",
    name: "Martinique",
    isoCode: "MQ",
  },
  {
    currency: "MRO",
    phoneCode: "+222",
    name: "Mauritania",
    isoCode: "MR",
  },
  {
    currency: "MUR",
    phoneCode: "+230",
    name: "Mauritius",
    isoCode: "MU",
  },
  {
    currency: "EUR",
    phoneCode: "+262",
    name: "Mayotte",
    isoCode: "YT",
  },
  {
    currency: "MXN",
    phoneCode: "+52",
    name: "Mexico",
    isoCode: "MX",
  },
  {
    currency: "USD",
    phoneCode: "+691",
    name: "Micronesia",
    isoCode: "FM",
  },
  {
    currency: "MDL",
    phoneCode: "+373",
    name: "Moldova",
    isoCode: "MD",
  },
  {
    currency: "EUR",
    phoneCode: "+377",
    name: "Monaco",
    isoCode: "MC",
  },
  {
    currency: "MNT",
    phoneCode: "+976",
    name: "Mongolia",
    isoCode: "MN",
  },
  {
    currency: "EUR",
    phoneCode: "+382",
    name: "Montenegro",
    isoCode: "ME",
  },
  {
    currency: "XCD",
    phoneCode: "+1-664",
    name: "Montserrat",
    isoCode: "MS",
  },
  {
    currency: "MAD",
    phoneCode: "+212",
    name: "Morocco",
    isoCode: "MA",
  },
  {
    currency: "MZN",
    phoneCode: "+258",
    name: "Mozambique",
    isoCode: "MZ",
  },
  {
    currency: "MMK",
    phoneCode: "+95",
    name: "Myanmar",
    isoCode: "MM",
  },
  {
    currency: "NAD",
    phoneCode: "+264",
    name: "Namibia",
    isoCode: "NA",
  },
  {
    currency: "AUD",
    phoneCode: "+674",
    name: "Nauru",
    isoCode: "NR",
  },
  {
    currency: "NPR",
    phoneCode: "+977",
    name: "Nepal",
    isoCode: "NP",
  },
  {
    currency: "USD",
    phoneCode: "+599",
    name: "Bonaire, Sint Eustatius and Saba",
    isoCode: "BQ",
  },
  {
    currency: "EUR",
    phoneCode: "+31",
    name: "Netherlands",
    isoCode: "NL",
  },
  {
    currency: "XPF",
    phoneCode: "+687",
    name: "New Caledonia",
    isoCode: "NC",
  },
  {
    currency: "NZD",
    phoneCode: "+64",
    name: "New Zealand",
    isoCode: "NZ",
  },
  {
    currency: "NIO",
    phoneCode: "+505",
    name: "Nicaragua",
    isoCode: "NI",
  },
  {
    currency: "XOF",
    phoneCode: "+227",
    name: "Niger",
    isoCode: "NE",
  },
  {
    currency: "NGN",
    phoneCode: "+234",
    name: "Nigeria",
    isoCode: "NG",
  },
  {
    currency: "NZD",
    phoneCode: "+683",
    name: "Niue",
    isoCode: "NU",
  },
  {
    currency: "AUD",
    phoneCode: "+672",
    name: "Norfolk Island",
    isoCode: "NF",
  },
  {
    currency: "USD",
    phoneCode: "+1-670",
    name: "Northern Mariana Islands",
    isoCode: "MP",
  },
  {
    currency: "NOK",
    phoneCode: "+47",
    name: "Norway",
    isoCode: "NO",
  },
  {
    currency: "OMR",
    phoneCode: "+968",
    name: "Oman",
    isoCode: "OM",
  },
  {
    currency: "PKR",
    phoneCode: "+92",
    name: "Pakistan",
    isoCode: "PK",
  },
  {
    currency: "USD",
    phoneCode: "+680",
    name: "Palau",
    isoCode: "PW",
  },
  {
    currency: "ILS",
    phoneCode: "+970",
    name: "Palestinian Territory Occupied",
    isoCode: "PS",
  },
  {
    currency: "PAB",
    phoneCode: "+507",
    name: "Panama",
    isoCode: "PA",
  },
  {
    currency: "PGK",
    phoneCode: "+675",
    name: "Papua new Guinea",
    isoCode: "PG",
  },
  {
    currency: "PYG",
    phoneCode: "+595",
    name: "Paraguay",
    isoCode: "PY",
  },
  {
    currency: "PEN",
    phoneCode: "+51",
    name: "Peru",
    isoCode: "PE",
  },
  {
    currency: "PHP",
    phoneCode: "+63",
    name: "Philippines",
    isoCode: "PH",
  },
  {
    currency: "NZD",
    phoneCode: "+870",
    name: "Pitcairn Island",
    isoCode: "PN",
  },
  {
    currency: "PLN",
    phoneCode: "+48",
    name: "Poland",
    isoCode: "PL",
  },
  {
    currency: "EUR",
    phoneCode: "+351",
    name: "Portugal",
    isoCode: "PT",
  },
  {
    currency: "USD",
    phoneCode: "+1-787 and 1-939",
    name: "Puerto Rico",
    isoCode: "PR",
  },
  {
    currency: "QAR",
    phoneCode: "+974",
    name: "Qatar",
    isoCode: "QA",
  },
  {
    currency: "EUR",
    phoneCode: "+262",
    name: "Reunion",
    isoCode: "RE",
  },
  {
    currency: "RON",
    phoneCode: "+40",
    name: "Romania",
    isoCode: "RO",
  },
  {
    currency: "RUB",
    phoneCode: "+7",
    name: "Russia",
    isoCode: "RU",
  },
  {
    currency: "RWF",
    phoneCode: "+250",
    name: "Rwanda",
    isoCode: "RW",
  },
  {
    currency: "SHP",
    phoneCode: "+290",
    name: "Saint Helena",
    isoCode: "SH",
  },
  {
    currency: "XCD",
    phoneCode: "+1-869",
    name: "Saint Kitts And Nevis",
    isoCode: "KN",
  },
  {
    currency: "XCD",
    phoneCode: "+1-758",
    name: "Saint Lucia",
    isoCode: "LC",
  },
  {
    currency: "EUR",
    phoneCode: "+508",
    name: "Saint Pierre and Miquelon",
    isoCode: "PM",
  },
  {
    currency: "XCD",
    phoneCode: "+1-784",
    name: "Saint Vincent And The Grenadines",
    isoCode: "VC",
  },
  {
    currency: "EUR",
    phoneCode: "+590",
    name: "Saint-Barthelemy",
    isoCode: "BL",
  },
  {
    currency: "EUR",
    phoneCode: "+590",
    name: "Saint-Martin (French part)",
    isoCode: "MF",
  },
  {
    currency: "WST",
    phoneCode: "+685",
    name: "Samoa",
    isoCode: "WS",
  },
  {
    currency: "EUR",
    phoneCode: "+378",
    name: "San Marino",
    isoCode: "SM",
  },
  {
    currency: "STD",
    phoneCode: "+239",
    name: "Sao Tome and Principe",
    isoCode: "ST",
  },
  {
    currency: "SAR",
    phoneCode: "+966",
    name: "Saudi Arabia",
    isoCode: "SA",
  },
  {
    currency: "XOF",
    phoneCode: "+221",
    name: "Senegal",
    isoCode: "SN",
  },
  {
    currency: "RSD",
    phoneCode: "+381",
    name: "Serbia",
    isoCode: "RS",
  },
  {
    currency: "SCR",
    phoneCode: "+248",
    name: "Seychelles",
    isoCode: "SC",
  },
  {
    currency: "SLL",
    phoneCode: "+232",
    name: "Sierra Leone",
    isoCode: "SL",
  },
  {
    currency: "SGD",
    phoneCode: "+65",
    name: "Singapore",
    isoCode: "SG",
  },
  {
    currency: "EUR",
    phoneCode: "+421",
    name: "Slovakia",
    isoCode: "SK",
  },
  {
    currency: "EUR",
    phoneCode: "+386",
    name: "Slovenia",
    isoCode: "SI",
  },
  {
    currency: "SBD",
    phoneCode: "+677",
    name: "Solomon Islands",
    isoCode: "SB",
  },
  {
    currency: "SOS",
    phoneCode: "+252",
    name: "Somalia",
    isoCode: "SO",
  },
  {
    currency: "ZAR",
    phoneCode: "+27",
    name: "South Africa",
    isoCode: "ZA",
  },
  {
    currency: "GBP",
    phoneCode: "+500",
    name: "South Georgia",
    isoCode: "GS",
  },
  {
    currency: "SSP",
    phoneCode: "+211",
    name: "South Sudan",
    isoCode: "SS",
  },
  {
    currency: "EUR",
    phoneCode: "+34",
    name: "Spain",
    isoCode: "ES",
  },
  {
    currency: "LKR",
    phoneCode: "+94",
    name: "Sri Lanka",
    isoCode: "LK",
  },
  {
    currency: "SDG",
    phoneCode: "+249",
    name: "Sudan",
    isoCode: "SD",
  },
  {
    currency: "SRD",
    phoneCode: "+597",
    name: "Suriname",
    isoCode: "SR",
  },
  {
    currency: "NOK",
    phoneCode: "+47",
    name: "Svalbard And Jan Mayen Islands",
    isoCode: "SJ",
  },
  {
    currency: "SZL",
    phoneCode: "+268",
    name: "Swaziland",
    isoCode: "SZ",
  },
  {
    currency: "SEK",
    phoneCode: "+46",
    name: "Sweden",
    isoCode: "SE",
  },
  {
    currency: "CHF",
    phoneCode: "+41",
    name: "Switzerland",
    isoCode: "CH",
  },
  {
    currency: "SYP",
    phoneCode: "+963",
    name: "Syria",
    isoCode: "SY",
  },
  {
    currency: "TWD",
    phoneCode: "+886",
    name: "Taiwan",
    isoCode: "TW",
  },
  {
    currency: "TJS",
    phoneCode: "+992",
    name: "Tajikistan",
    isoCode: "TJ",
  },
  {
    currency: "TZS",
    phoneCode: "+255",
    name: "Tanzania",
    isoCode: "TZ",
  },
  {
    currency: "THB",
    phoneCode: "+66",
    name: "Thailand",
    isoCode: "TH",
  },
  {
    currency: "XOF",
    phoneCode: "+228",
    name: "Togo",
    isoCode: "TG",
  },
  {
    currency: "NZD",
    phoneCode: "+690",
    name: "Tokelau",
    isoCode: "TK",
  },
  {
    currency: "TOP",
    phoneCode: "+676",
    name: "Tonga",
    isoCode: "TO",
  },
  {
    currency: "TTD",
    phoneCode: "+1-868",
    name: "Trinidad And Tobago",
    isoCode: "TT",
  },
  {
    currency: "TND",
    phoneCode: "+216",
    name: "Tunisia",
    isoCode: "TN",
  },
  {
    currency: "TRY",
    phoneCode: "+90",
    name: "Turkey",
    isoCode: "TR",
  },
  {
    currency: "TMT",
    phoneCode: "+993",
    name: "Turkmenistan",
    isoCode: "TM",
  },
  {
    currency: "USD",
    phoneCode: "+1-649",
    name: "Turks And Caicos Islands",
    isoCode: "TC",
  },
  {
    currency: "AUD",
    phoneCode: "+688",
    name: "Tuvalu",
    isoCode: "TV",
  },
  {
    currency: "UGX",
    phoneCode: "+256",
    name: "Uganda",
    isoCode: "UG",
  },
  {
    currency: "UAH",
    phoneCode: "+380",
    name: "Ukraine",
    isoCode: "UA",
  },
  {
    currency: "AED",
    phoneCode: "+971",
    name: "United Arab Emirates",
    isoCode: "AE",
  },
  {
    currency: "GBP",
    phoneCode: "+44",
    name: "United Kingdom",
    isoCode: "GB",
  },
  {
    currency: "USD",
    phoneCode: "+1",
    name: "United States",
    isoCode: "US",
  },
  {
    currency: "USD",
    phoneCode: "+1",
    name: "United States Minor Outlying Islands",
    isoCode: "UM",
  },
  {
    currency: "UYU",
    phoneCode: "+598",
    name: "Uruguay",
    isoCode: "UY",
  },
  {
    currency: "UZS",
    phoneCode: "+998",
    name: "Uzbekistan",
    isoCode: "UZ",
  },
  {
    currency: "VUV",
    phoneCode: "+678",
    name: "Vanuatu",
    isoCode: "VU",
  },
  {
    currency: "EUR",
    phoneCode: "+379",
    name: "Vatican City State (Holy See)",
    isoCode: "VA",
  },
  {
    currency: "VEF",
    phoneCode: "+58",
    name: "Venezuela",
    isoCode: "VE",
  },
  {
    currency: "VND",
    phoneCode: "+84",
    name: "Vietnam",
    isoCode: "VN",
  },
  {
    currency: "USD",
    phoneCode: "+1-284",
    name: "Virgin Islands (British)",
    isoCode: "VG",
  },
  {
    currency: "USD",
    phoneCode: "+1-340",
    name: "Virgin Islands (US)",
    isoCode: "VI",
  },
  {
    currency: "XPF",
    phoneCode: "+681",
    name: "Wallis And Futuna Islands",
    isoCode: "WF",
  },
  {
    currency: "MAD",
    phoneCode: "+212",
    name: "Western Sahara",
    isoCode: "EH",
  },
  {
    currency: "YER",
    phoneCode: "+967",
    name: "Yemen",
    isoCode: "YE",
  },
  {
    currency: "ZMW",
    phoneCode: "+260",
    name: "Zambia",
    isoCode: "ZM",
  },
  {
    currency: "ZWL",
    phoneCode: "+263",
    name: "Zimbabwe",
    isoCode: "ZW",
  },
  {
    currency: "EUR",
    phoneCode: "+383",
    name: "Kosovo",
    isoCode: "XK",
  },
  {
    currency: "ANG",
    phoneCode: "+599",
    name: "Curaçao",
    isoCode: "CW",
  },
  {
    currency: "ANG",
    phoneCode: "+1721",
    name: "Sint Maarten (Dutch part)",
    isoCode: "SX",
  },
];
